formats:
  default: "{TAG}&8[&7{POINTS}&8] &7{PLAYER}&8: &f{MESSAGE}"
  vip: "{TAG}&8[&7{POINTS}&8] {RANK} &7{PLAYER}&8: &f{MESSAGE}"
  svip: "{TAG}&8[&7{POINTS}&8] {RANK} &7{PLAYER}&8: &f{MESSAGE}"
  sponsor: "{TAG}&8[&7{POINTS}&8] {RANK} &7{PLAYER}&8: &f{MESSAGE}"
  hard: "{TAG}&8[&7{POINTS}&8] {RANK} &7{PLAYER}&8: &f{MESSAGE}"
  testhelper: "{TAG}&8[&7{POINTS}&8] {RANK} &b{PLAYER}&8: &f{MESSAGE}"
  helper: "{TAG}&8[&7{POINTS}&8] {RANK} &b{PLAYER}&8: &f{MESSAGE}"
  moderator: "{RANK} &2{PLAYER}&8: &f{MESSAGE}"
  admin: "{RANK} &c{PLAYER}&8: &f{MESSAGE}"
  headadmin: "{RANK} &4{PLAYER}&8: &c{MESSAGE}"
  root: "{RANK} &4{PLAYER}&8: &c{MESSAGE}"

prefix:
  default: ""
  vip: "&eVIP"
  svip: "&6SVIP"
  sponsor: "&5SPONSOR"
  hard: "&3HARD"
  testhelper: "&b&lT&3&lH"
  helper: "&3&lHELPER"
  moderator: "&2&lMOD"
  admin: "&c&lADMIN"
  headadmin: "&4&lH@"
  root: "&4&lROOT"